version: '3'

services:
  db:
    image: postgres
    container_name: nest-eats
    restart: always
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nuber-eats

